"""add status_processamento to ProcessoSEI

Revision ID: 1e899f8aaaa4
Revises: c4fddbe7b84c
Create Date: 2026-07-05 10:37:51.674963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e899f8aaaa4'
down_revision = 'c4fddbe7b84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_processamento', sa.String(length=50), nullable=True))
    
    op.execute("UPDATE processos_sei SET status_processamento = 'Concluído'")
    
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.alter_column('status_processamento', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.drop_column('status_processamento')

    # ### end Alembic commands ###
