"""add tempo_analise to ProcessoSEI

Revision ID: 3b6e74ba7132
Revises: 1e899f8aaaa4
Create Date: 2026-07-05 13:19:15.227039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6e74ba7132'
down_revision = '1e899f8aaaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tempo_analise', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.drop_column('tempo_analise')

    # ### end Alembic commands ###
