"""altera tipo prioridade

Revision ID: 430fa6f34049
Revises: 3d5ebf4dedc9
Create Date: 2026-10-05 17:33:18.579926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430fa6f34049'
down_revision = '3d5ebf4dedc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remetentes', schema=None) as batch_op:
        batch_op.alter_column('prefixo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('prioridade',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remetentes', schema=None) as batch_op:
        batch_op.alter_column('prioridade',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('cor',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('prefixo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
