"""Add prompt_configs table

Revision ID: 49af975cc515
Revises: e5a3c7295cbb
Create Date: 2026-06-30 19:49:44.499099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49af975cc515'
down_revision = 'e5a3c7295cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_configs')
    # ### end Alembic commands ###
