"""add prazos e remetentes columns to processo_sei

Revision ID: 4ab74eceb96d
Revises: e17e0f461c85
Create Date: 2026-09-30 17:43:41.503674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab74eceb96d'
down_revision = 'e17e0f461c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_emissao_documento', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prazo_legal_dias', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_inicio_analise', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('remetente', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.drop_column('remetente')
        batch_op.drop_column('data_inicio_analise')
        batch_op.drop_column('prazo_legal_dias')
        batch_op.drop_column('data_emissao_documento')

    # ### end Alembic commands ###
