"""Adiciona coluna erro_processamento na tabela processos_sei

Revision ID: 6044237836d7
Revises: 3b6e74ba7132
Create Date: 2026-07-20 18:15:27.565567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6044237836d7'
down_revision = '3b6e74ba7132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erro_processamento', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.drop_column('erro_processamento')

    # ### end Alembic commands ###
