"""add arquivoPdf to processos_sei

Revision ID: c4fddbe7b84c
Revises: a80ace40ed0c
Create Date: 2026-07-01 10:14:18.871523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fddbe7b84c'
down_revision = 'a80ace40ed0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivoPdf', sa.String(length=255), nullable=True))
        batch_op.alter_column('partes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.alter_column('partes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('arquivoPdf')

    # ### end Alembic commands ###
