"""add complexidade columns

Revision ID: e17e0f461c85
Revises: 0d0a33a45e21
Create Date: 2026-09-26 19:07:29.400421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17e0f461c85'
down_revision = '0d0a33a45e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.add_column(sa.Column('complexidade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('complexidade_justificativa', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processos_sei', schema=None) as batch_op:
        batch_op.drop_column('complexidade_justificativa')
        batch_op.drop_column('complexidade')

    # ### end Alembic commands ###
