"""initial migration

Revision ID: e5a3c7295cbb
Revises: 
Create Date: 2026-06-30 12:16:38.716273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a3c7295cbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos_sei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('assunto', sa.String(length=200), nullable=False),
    sa.Column('partes', sa.String(length=255), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dataRecebimento', sa.DateTime(), nullable=False),
    sa.Column('prioridade', sa.String(length=50), nullable=False),
    sa.Column('prioridade_original', sa.String(length=50), nullable=True),
    sa.Column('foi_alterado', sa.Boolean(), nullable=False),
    sa.Column('iaConfidence', sa.Float(), nullable=False),
    sa.Column('analista', sa.String(length=100), nullable=True),
    sa.Column('dataRevisao', sa.DateTime(), nullable=True),
    sa.Column('dataPreAnalise', sa.DateTime(), nullable=False),
    sa.Column('iaSugestao', sa.Text(), nullable=True),
    sa.Column('jurisprudenciasSugeridas', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('resumo_batch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('triggered_by', sa.String(length=120), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_seis', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('sei_ids_json', sa.Text(), nullable=False),
    sa.Column('logs_json', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumo_batch_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('last_run_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumo_reexecution_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sei_id', sa.String(length=40), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_by', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumo_reexecution_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumo_reexecution_requests_sei_id'), ['sei_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('resumo_tecnico_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sei_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('minuta', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('batch_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_run_id'], ['resumo_batch_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resumo_tecnico_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumo_tecnico_versions_sei_id'), ['sei_id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    with op.batch_alter_table('resumo_tecnico_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumo_tecnico_versions_sei_id'))

    op.drop_table('resumo_tecnico_versions')
    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('resumo_reexecution_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumo_reexecution_requests_sei_id'))

    op.drop_table('resumo_reexecution_requests')
    op.drop_table('resumo_batch_schedules')
    op.drop_table('resumo_batch_runs')
    op.drop_table('processos_sei')
    # ### end Alembic commands ###
